DetachHead/pytest-robotframework

- .gitignore
- pytest_robotframework/pytest_robotframework.py
> Fix double running

- pytest_robotframework/pytest_robotframework.py
- tests/test_robotframework.py
> refactor to call the pytest runtest protocol hooks

- pytest_robotframework/__init__.py
- pytest_robotframework/pytest_robotframework.py
- tests/test_pytest_robotframework.py
> Keyword and markers

- poetry.lock
- pyproject.toml
- pytest_robotframework/pytest_robotframework.py
- tests/test_pytest_robotframework.py
> Fix keyword unique names

- README.md
- pytest_robotframework/pytest_robotframework.py
- tests/test_pytest_robotframework.py
> fix parameterize

- README.md
- poetry.lock
- pyproject.toml
- pytest_robotframework/_common.py
- pytest_robotframework/_fake_robot_library.py
- pytest_robotframework/_python.py
- pytest_robotframework/_robot.py
- pytest_robotframework/pytest_robotframework.py
- tests/test_python.py
- tests/test_robot.py
- tests/utils.py
> Run robot files

- pytest_robotframework/__init__.py
- pytest_robotframework/pytest_robotframework.py
- tests/test_python.py
> support importing robot resources from python files

- pyproject.toml
- pytest_robotframework/_common.py
- pytest_robotframework/_python.py
- pytest_robotframework/_robot.py
- pytest_robotframework/pytest_robotframework.py
- tests/test_python.py
- tests/test_robot.py
> Dont run robot twice

- pytest_robotframework/_common.py
- tests/fixtures/test_python/test_xfail_fails/test_foo.py
- tests/fixtures/test_python/test_xfail_fails/tox.ini
- tests/fixtures/test_python/test_xfail_fails_no_reason/test_foo.py
- tests/fixtures/test_python/test_xfail_fails_no_reason/tox.ini
- tests/fixtures/test_python/test_xfail_passes/test_foo.py
- tests/fixtures/test_python/test_xfail_passes/tox.ini
- tests/fixtures/test_python/test_xfail_passes_no_reason/test_foo.py
- tests/fixtures/test_python/test_xfail_passes_no_reason/tox.ini
- tests/test_python.py
- tests/utils.py
> support xfail

- pytest_robotframework/_common.py
- tests/fixtures/test_python/test_no_tests_found_when_tests_exist.py
- tests/fixtures/test_robot/test_no_tests_found_when_tests_exist.robot
- tests/test_common.py
- tests/test_python.py
- tests/test_robot.py
- tests/utils.py
> fix fake test not being deleted when no tests are found

- pytest_robotframework/_internal/plugin.py
- pytest_robotframework/_internal/robot_classes.py
- tests/fixtures/test_python/test_error_moment.py
- tests/fixtures/test_python/test_error_moment_and_second_test.py
- tests/fixtures/test_python/test_error_moment_exitonerror.py
- tests/fixtures/test_python/test_error_moment_exitonerror_multiple_tests.py
- tests/fixtures/test_python/test_error_moment_setup/conftest.py
- tests/fixtures/test_python/test_error_moment_setup/test_foo.py
- tests/fixtures/test_python/test_error_moment_teardown/conftest.py
- tests/fixtures/test_python/test_error_moment_teardown/test_foo.py
- tests/test_python.py
- tests/utils.py
> fix errors not causing pytest to fail

- pyproject.toml
- pytest_robotframework/__init__.py
- pytest_robotframework/_internal/robot_classes.py
- pytest_robotframework/_internal/robot_library.py
- pytest_robotframework/_internal/robot_utils.py
- pytest_robotframework/_internal/utils.py
- tests/fixtures/test_robot/test_keyword_decorator/bar.robot
- tests/fixtures/test_robot/test_keyword_decorator/foo.py
- tests/fixtures/test_robot/test_keyword_decorator_and_other_decorator/bar.robot
- tests/fixtures/test_robot/test_keyword_decorator_and_other_decorator/foo.py
- tests/test_robot.py
> fix double keywording

- .vscode/launch.json
- pytest_robotframework/_internal/plugin.py
- pytest_robotframework/_internal/pytest_exception_getter.py
- pytest_robotframework/_internal/robot_library.py
- tests/fixtures/test_python/test_traceback.py
- tests/test_python.py
> fix tracebacks in robot log

- README.md
- pytest_robotframework/__init__.py
> include the contents of the readme on the docs site

- .github/workflows/check and publish.yaml
- .vscode/tasks.json
- pdm.lock
- pyproject.toml
- pytest_robotframework/__init__.py
- pytest_robotframework/_internal/robot_classes.py
- pytest_robotframework/_internal/robot_library.py
- pytest_robotframework/_internal/robot_utils.py
- pytest_robotframework/_internal/utils.py
- tests/test_python.py
- tests/test_robot.py
> bump basedmypy

- .github/workflows/check and publish.yaml
- .vscode/tasks.json
- README.md
- pdm.lock
- pyproject.toml
- pytest_robotframework/__init__.py
- pytest_robotframework/_internal/pytest_robot_items.py
- pytest_robotframework/_internal/robot_classes.py
- pytest_robotframework/_internal/robot_library.py
- pytest_robotframework/_internal/robot_utils.py
- tests/fixtures/test_python/test_as_keyword_context_manager_try_except.py
- tests/fixtures/test_python/test_catch_errors_decorator/conftest.py
- tests/fixtures/test_python/test_catch_errors_decorator_with_non_instance_method/conftest.py
- tests/fixtures/test_python/test_keyword_decorator_context_manager_that_doesnt_suppress.py
- tests/fixtures/test_python/test_keyword_decorator_context_manager_that_raises_in_exit.py
- tests/fixtures/test_python/test_keyword_raises.py
- tests/fixtures/test_python/test_keywordify_context_manager.py
- tests/fixtures/test_python/test_keywordify_keyword_inside_context_manager.py
- tests/fixtures/test_python/test_listener_calls_log_file/Listener.py
- tests/fixtures/test_python/test_listener_decorator/conftest.py
- tests/fixtures/test_python/test_setup_passes/conftest.py
- tests/fixtures/test_python/test_setup_passes/test_foo.py
- tests/fixtures/test_python/test_teardown_passes/conftest.py
- tests/fixtures/test_python/test_teardown_passes/test_foo.py
- tests/fixtures/test_robot/test_keyword_decorator/foo.py
- tests/fixtures/test_robot/test_keyword_decorator_and_other_decorator/foo.py
- tests/fixtures/test_robot/test_listener_calls_log_file/Listener.py
> robotframework 7.0

- pyproject.toml
- pytest_robotframework/__init__.py
- pytest_robotframework/_internal/robot_classes.py
- tests/conftest.py
- tests/fixtures/test_python/test_fixture_scope.py
- tests/test_python.py
> fix class/module scoped fixtures being re-executed on every test

- pytest_robotframework/_internal/xdist_utils.py
- tests/conftest.py
- tests/fixtures/test_python/test_xdist_n_0.py
- tests/test_python.py
- tests/test_robot.py
> fix crash when disabling xdist with `-n 0`

- .idea/python-project.iml
- pdm.lock
- pyproject.toml
- pytest_robotframework/_internal/plugin.py
- pytest_robotframework/_internal/robot_classes.py
- tests/conftest.py
- tests/fixtures/test_python/test_ansi.py
- tests/test_python.py
> Support ansi codes in the log

- pyproject.toml
- pytest_robotframework/__init__.py
- pytest_robotframework/_internal/patches/__init__.py
- pytest_robotframework/_internal/patches/pytest.py
- pytest_robotframework/_internal/patches/robot.py
- pytest_robotframework/_internal/plugin.py
- pytest_robotframework/_internal/robot_utils.py
- pytest_robotframework/_internal/utils.py
- tests/fixtures/test_python/test_full_stack_keyword_context_manager.py
- tests/fixtures/test_python/test_full_stack_keyword_decorator.py
- tests/test_python.py
> fix exceptions raised inside keywords not including the full trace

- pytest_robotframework/__init__.py
- pytest_robotframework/_internal/patches/robot.py
- pytest_robotframework/_internal/robot_library.py
- tests/fixtures/test_python/test_nested_keyword_that_fails.py
- tests/test_python.py
> fix duplicate exceptions in log

- pytest_robotframework/_internal/plugin.py
- tests/fixtures/test_python/test_set_log_level.py
- tests/test_python.py
> fix `BuiltIn().set_log_level` when running with xdist

- .vscode/launch.json
- pytest_robotframework/_internal/pytest/plugin.py
- pytest_robotframework/_internal/robot/listeners_and_suite_visitors.py
- tests/fixtures/test_python/test_two_tests_specified_by_full_path_in_different_files/test_bar.py
- tests/fixtures/test_python/test_two_tests_specified_by_full_path_in_different_files/test_foo.py
- tests/test_python.py
> fix crash when running with full paths to multiple different tests from different files

- pytest_robotframework/_internal/pytest/exception_getter.py
- pytest_robotframework/_internal/pytest/plugin.py
- tests/fixtures/test_python/test_pytest_runtest_protocol_item_hook/foo/conftest.py
- tests/fixtures/test_python/test_pytest_runtest_protocol_session_hook/conftest.py
> convert all `hookwrapper`s to new `wrapper`s

- .vscode/extensions.json
- .vscode/settings.json
- README.md
waiting for https://github.com/d-biehl/robotcode/pull/205 to be merged
> switch to robotcode extension

- pyproject.toml
- pytest_robotframework/_internal/robot/listeners_and_suite_visitors.py
- tests/fixtures/test_python/test_class_three_tests_one_fail.py
- tests/test_python.py
> fix crash caused by xdist workers not running the correct tests in some cases

- pytest_robotframework/_internal/robot/utils.py
- tests/fixtures/test_common/test_robot_file_and_python_file/foo.robot
- tests/fixtures/test_common/test_robot_file_and_python_file/test_bar.py
- tests/fixtures/test_python/test_run_two_files/test_a.py
- tests/fixtures/test_python/test_run_two_files/test_b.py
- tests/fixtures/test_robot/test_run_two_files/a.robot
- tests/fixtures/test_robot/test_run_two_files/b.robot
- tests/test_common.py
- tests/test_python.py
- tests/test_robot.py
> fix crash when running with python and robot file, and fix no tests being run when running two robot files

- pytest_robotframework/_internal/pytest/plugin.py
- tests/test_python.py
> fix the terminal summary with a custom outputdir

- pytest_robotframework/_internal/robot/listeners_and_suite_visitors.py
- tests/fixtures/test_robot/test_keyword_decorator_class_library/ClassLibrary.py
- tests/fixtures/test_robot/test_keyword_decorator_class_library/asdf.robot
- tests/test_robot.py
> fix crash with keyword decorator on class libraries
